# Setup
title:        La Frikitiva
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "http://lafrikitiva.com"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Frikitiva
  url:        http://lafrikitiva.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
